# Generated by Django 3.2.6 on 2021-08-31 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210831_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.person'),
        ),
    ]
