# Generated by Django 3.2.6 on 2021-08-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='instance',
            name='card',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='type',
            new_name='tipe',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.AddField(
            model_name='singular',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.card'),
        ),
        migrations.AddField(
            model_name='singular',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck', to='accounts.profile'),
        ),
    ]
