# Generated by Django 3.2.6 on 2021-08-29 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('card', '0002_auto_20210829_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singular',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card'),
        ),
        migrations.AlterField(
            model_name='singular',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='accounts.profile'),
        ),
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='him', to='accounts.profile')),
                ('card_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_want', to='card.singular')),
                ('card_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_card', to='card.singular')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to='accounts.profile')),
            ],
        ),
    ]
