# Generated by Django 3.2.6 on 2021-08-30 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('card', '0003_auto_20210829_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('singular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.singular')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('card_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.singular')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='card.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Trading',
        ),
        migrations.AddField(
            model_name='answer',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='card.response'),
        ),
    ]
