# Generated by Django 3.2.6 on 2021-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20210830_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='O', max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=50),
        ),
    ]
