# Generated by Django 3.2.6 on 2021-08-31 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_auto_20210831_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceupdate',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='response',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='card_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.singular'),
        ),
    ]
